cc_library(
    name="functions",
    hdrs = ["func.h"], # sample function header file
    srcs = ["func.cpp"], # sample function source code
    visibility = ["//visibility:public"], # should be set to package_group instead of public
)